---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    login: &login
      server_url: https://10.101.4.6.27
      username: admin
      password: P@$$w0rd$1
      validate_certs: no
    organization: OAB
    lifecycle_environment: undef
    current_lifecycle_environment: undef
    content_view: undef

  tasks:
  - name: Promote Content View
    redhat.satellite.content_view_version:
      <<: *login
      content_view: "{{ content_view }}"
      organization: "{{ organization }}"
      lifecycle_environments: "{{ lifecycle_environment }}"
      current_lifecycle_environment: "{{ current_lifecycle_environment }}"
